# Generated by Django 6.0.4 on 2026-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
