# Generated by Django 6.0.4 on 2026-04-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
