# Generated by Django 6.0.4 on 2026-04-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_deck_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
