# Generated by Django 6.0.4 on 2026-04-26 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_description_alter_deck_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='deck',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
