# Generated by Django 6.0.4 on 2026-04-26 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_options_alter_deck_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='starred_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='starred_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
