# Generated by Django 6.0.4 on 2026-04-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cardprogress_card_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='last_inputs',
            field=models.JSONField(default=list),
        ),
    ]
